schema = 3

[mod]
  [mod.'charm.land/bubbles/v2']
    version = 'v2.1.0'
    hash = 'sha256-2OmqpBrl+taOJzAhVM6OReLmoYRxZOXx9JqFNjQjsPA='

  [mod.'charm.land/bubbletea/v2']
    version = 'v2.0.6'
    hash = 'sha256-1jxXmcnI4peUE0Xs3HGe57pIhRONx235aAaeqm2r434='

  [mod.'charm.land/glamour/v2']
    version = 'v2.0.0'
    hash = 'sha256-CZYlNGw2MihqnSHf1Xxqz55NnqW9fVpLxyvLItryIw4='

  [mod.'charm.land/lipgloss/v2']
    version = 'v2.0.3'
    hash = 'sha256-/RFkSUscU3NwymzT+PfizGf3XyQIdVGQlX7vxktCUGk='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.24.1'
    hash = 'sha256-DufsljWRKireFuLFcnPozuF0N3UoRYGlEfNFMD+z0ng='

  [mod.'github.com/anotherhadi/ilovetui']
    version = 'v0.1.6'
    hash = 'sha256-7E+7UFks5vM3XWCvX2joFmHGcW7qqnoox6ZPFglaLO4='

  [mod.'github.com/atotto/clipboard']
    version = 'v0.1.4'
    hash = 'sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk='

  [mod.'github.com/aymerick/douceur']
    version = 'v0.2.0'
    hash = 'sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.3'
    hash = 'sha256-y+QDUxGOKhugEMQLRUTZYT2C+wKqYHnMLJ44jbh7+JA='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20260511121909-c840852527f3'
    hash = 'sha256-oWEEaaetCmXvflD03MWy8qD105Kd62iI62+lxofE9Ns='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.7'
    hash = 'sha256-q8BZJq4K7NE5ETocN9/G/EoV0dUyD703ONSfHiUYzWQ='

  [mod.'github.com/charmbracelet/x/exp/slice']
    version = 'v0.0.0-20260517005351-920740d613be'
    hash = 'sha256-bMsbEzP1gHA2OJx4zMYZUI3UFhcTG+mcFm8rRY+Khh8='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.11.0'
    hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.12.0'
    hash = 'sha256-PVX2rDCkiG0vyA1CbDi3bzLeZ2T8hcqJv3pZ5YwGzMI='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.10.1'
    hash = 'sha256-6LBLgsh4nKkMpgRKVsYFEaGDSU1fncBcWVSjKBdfgjU='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.5.0'
    hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.2.2'
    hash = 'sha256-j+LicPlXcB1R3oVFPa8cd4yVJLpBx+ca5gXmHqOJSN8='

  [mod.'github.com/gorilla/css']
    version = 'v1.0.1'
    hash = 'sha256-6JwNHqlY2NpZ0pSQTyYPSpiNqjXOdFHqrUT10sv3y8A='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.4.0'
    hash = 'sha256-i/3GDHKEMLCy0kc3mtyk58UWYOPmKoUVaq6QCAWXKP0='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.23'
    hash = 'sha256-SmChZ2U1aR8pW3LPhdM7KcVF5TO6VcHgRzBtUXbBWJA='

  [mod.'github.com/microcosm-cc/bluemonday']
    version = 'v1.0.27'
    hash = 'sha256-EZSya9FLPQ83CL7N2cZy21fdS35hViTkiMK5f3op8Es='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.1'
    hash = 'sha256-5H8+UOtPOs+Yc+8oVT/3bugCCdbq3jFMH6eOW8dadyg='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.12.0'
    hash = 'sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws='

  [mod.'github.com/sirupsen/logrus']
    version = 'v1.9.4'
    hash = 'sha256-ltRvmtM3XTCAFwY0IesfRqYIivyXPPuvkFjL4ARh1wg='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.8.2'
    hash = 'sha256-LoWfW1Tb6mNuMR7SoA/4SJv4pTKfsVXqeXEVm4uEQ7Q='

  [mod.'github.com/yuin/goldmark-emoji']
    version = 'v1.0.6'
    hash = 'sha256-+d6bZzOPE+JSFsZbQNZMCWE+n3jgcQnkPETVk47mxSY='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/net']
    version = 'v0.55.0'
    hash = 'sha256-Phi2mSmBGOJcvqPPAit3uqF3UP8SKRI9dHj6yTM3s5s='

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/sys']
    version = 'v0.45.0'
    hash = 'sha256-hkBoNazrDA67ER6sWhb+EKxx9nJ24+nz3zGy+zT5Hvw='

  [mod.'golang.org/x/text']
    version = 'v0.37.0'
    hash = 'sha256-8XDOnlPIybcDRy89fkjG5VqtIt5Ku+LmaqYhgKl7i1E='

  [mod.'gopkg.in/check.v1']
    version = 'v1.0.0-20201130134442-10cb98267c6c'
    hash = 'sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
